name: ecommmerce
description: "Flutter Ecommerce Project By Sidahmed Belkadi."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Utility Packages
  logger: ^2.2.0
  http: ^1.2.1
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  toastification: ^1.2.1
  shared_preferences: ^2.2.2
  flutter_otp_text_field: ^1.1.2+1
  lottie: ^3.1.0
  iconsax: ^0.0.8
  flutter_animate: ^4.5.0
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1
  flutter_staggered_animations: ^1.1.1
  readmore: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#

  assets:
    - assets/images/
    - assets/animations/
    - assets/banners/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
